config/urls.py
from django.contrib import admin
from django.urls import include, path
from config.views import HomeView

urlpatterns = [
    path("", HomeView.as_view(), name='home'),
    path("kiosk/", include("kiosk.urls")),
    path("admin/", admin.site.urls),
]

kiosk/urls.py
from django.urls import path

from . import views

app_name = 'kiosk'

urlpatterns = [
    path("", views.cafe_menuLV.as_view(), name='menu_list'),
    path("drink/<int:pk>/", views.CreateOrderItemView.as_view(), name='menu_order'),
]

kiosk/models.py
from django.db import models
from datetime import date


# Create your models here.
class DrinkType(models.Model):
    type_name = models.CharField(max_length=100)

    def __str__(self):
        return self.type_name

# 음료 및 디저트 모델
class Drink(models.Model):
    type = models.ForeignKey(DrinkType, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    inventory = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Order(models.Model):
    # customer_id = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True) # customer_id가 사라지면 null로
    order_date = models.DateTimeField(auto_now_add=True)
    total_price = models.IntegerField(default=0)

    def __str__(self):
        return f"주문번호 {self.id}"

# 주문 상세 모델
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    drink = models.ForeignKey(Drink, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.drink.name} 주문 (주문: {self.order.id})"

# 결제 모델
class Payment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment_date = models.DateTimeField(auto_now_add=True)
    PAYMENT_CHOICES = [
        ('cash', '현금'),
        ('card', '카드'),
    ]
    payment_method = models.CharField(max_length=50, choices=PAYMENT_CHOICES)
    # total_price = models.IntegerField()

    def __str__(self):
        return f"{self.order} 결제"


class TodaySales(models.Model):
    order_date = models.DateField(default=date.today, unique=True)
    total_sales = models.IntegerField()

    def __str__(self):
        return f"{self.order_date} - 총 매출: {self.total_sales}"

config/views.py
from django.views.generic import TemplateView
from django.shortcuts import redirect
from kiosk.models import Order

class HomeView(TemplateView):
    template_name = 'home.html'
    
    def get(self, request, *args, **kwargs):
        # GET 요청을 받았을 때 실행될 코드
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        # POST 요청을 받았을 때 실행될 코드
        # 새로운 주문 생성
        order = Order.objects.create()
        # 생성된 주문의 ID를 사용하여 카페 메뉴 페이지로 리디렉션
        return redirect('kiosk:menu_list')

kiosk/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.urls import reverse_lazy
from django.http import HttpResponse, Http404 , HttpResponseRedirect
from django.db.models import Max

from kiosk.models import Drink, DrinkType, Order, OrderItem
from django.db.models import F

class cafe_menuLV(ListView):
    model = DrinkType
    template_name = 'kiosk/cafe_menu.html'
    


class CreateOrderItemView(CreateView):
    model = OrderItem
    fields = ['quantity']
    template_name = 'kiosk/orderitem_create.html'

    def get_latest_order(self):
    # 가장 최근에 생성된 주문을 가져오는 함수
        latest_order = Order.objects.latest('order_date')
        return latest_order
    
    def form_valid(self, form):
        order = self.get_latest_order()
        form.instance.order = get_object_or_404(Order, pk=order.pk)
        form.instance.drink = get_object_or_404(Drink, pk=self.kwargs['pk'])
        return super().form_valid(form)
    

    success_url = reverse_lazy('kiosk:menu_list')

kiosk/templates/kiosk/cafe_menu.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>멋사카페 메뉴</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        body, html {
            height: 100%;
            margin: 0;
            display: flex;
            justify-content: center;
            {% comment %} align-items: center; {% endcomment %}
            background-color: var(--bs-success-bg-subtle);
        }
        .long-button {
            width: 150px; /* 원하는 너비 설정 */
        }
    </style>
    </head>
    <body>
      <div class="container">
        <h1 class="text-center mt-5">카페 메뉴</h1>
            {% comment %} <div class="btn-group mt-3" role="group">
                <!-- Django 템플릿을 이용하여 메뉴 유형 버튼 생성 -->
                {% for drink_type in object_list %}
                    <button type="button" class="btn btn-success long-button">{{ drink_type.type_name }}</button>
                {% endfor %}
            </div> {% endcomment %}
        <br>
        <br>

      <div class="row row-cols-1 row-cols-md-4 g-4">
        {% for drink_type in object_list %}
        {% comment %} <h2>{{ drink_type.name }}</h2> {% endcomment %}
        {% for drink in drink_type.drink_set.all %}
          <div class="col">
            <div class="card border-success mb-3">
               {% comment %} <img src="{% static 'kiosk/img/' %}{{ drink.name }}.avif" class="card-img-top" alt="{{drink.name}}"> {% endcomment %}
               <img src="{% static 'kiosk/img/아이스 아메리카노.avif' %}" class="card-img-top" alt="{{drink.name}}">
                  <div class="card-body">
                    <h5 class="card-title">{{drink.name}}</h5>
                    <p class="card-text">가격: {{drink.price}}</p>
                    <a href="{% url 'kiosk:menu_order' drink.id %}" class="btn btn-success">주문하기</a>
                  </div>
                </div>
              </div>
          {% endfor %}
       {% endfor %}
      </div>

      </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

kiosk/templates/kiosk/orderitem_create.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="button" onclick="increaseQuantity()" class="btn btn-success">+</button>
    <button type="button" onclick="decreaseQuantity()" class="btn btn-success">-</button>
    <button type="submit" class="btn btn-success">주문담기</button>
    <a href="" class="btn btn-success">결제하기</a>
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    function increaseQuantity() {
        var quantityInput = $('#id_quantity');
        var currentValue = parseInt(quantityInput.val());
        quantityInput.val(currentValue + 1);
    }

    function decreaseQuantity() {
        var quantityInput = $('#id_quantity');
        var currentValue = parseInt(quantityInput.val());
        if (currentValue > 1) {
            quantityInput.val(currentValue - 1);
        }
    }
</script>

templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>멋사카페 홈</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        body, html {
            height: 100%;
            margin: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            background-color: var(--bs-success-bg-subtle);
        }
    </style>
    </head>
    <body>
    <div class = "container">
        <h1 class="text-success">안녕하세요 멋사카페입니다!</h1>
        <br>
        <div class="container text-center">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-success btn-lg">
                    주문하시겠습니까?
                </button>
            </form>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>